baseURL = "https://browniealice.github.io/blog/"
languageCode = "ja-JP"
title = "Alice in the Machine - Blog"
theme = "hugo_theme_robust"
publishDir = "docs"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"